# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import game_service_pb2 as game__service__pb2


class GameStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SayHello = channel.unary_unary(
        '/Game/SayHello',
        request_serializer=game__service__pb2.HelloRequest.SerializeToString,
        response_deserializer=game__service__pb2.HelloReply.FromString,
        )


class GameServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def SayHello(self, request, context):
    """Sends a greeting
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_GameServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SayHello': grpc.unary_unary_rpc_method_handler(
          servicer.SayHello,
          request_deserializer=game__service__pb2.HelloRequest.FromString,
          response_serializer=game__service__pb2.HelloReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Game', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
